# Site settings
title: Corikachu
email: corikachu at gmail.com
description: > # this means to ignore newlines until "baseurl:"
  즐겁게 개발하며 배운 것을 풀어놓는 Corikachu 블로그
baseurl: "" # the subpath of your site
# url: "https://corikachu.github.io" # the base hostname & protocol
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# Build settings
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:categories/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false


owner:
  name: Corikachu
  avatar: avatar.png
  avatar-width: 300
  avatar-height: 300
  job: "developer"
  bio: "세상을 즐겁게 살고픈 소신있는 개발자"
  email:
  disqus-shortname: corikachu
  twitter:
  facebook: corikachu
  google:
    plus:
    analytics: UA-80877473-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: corikachu
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: corikachu
  xing:
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  youtube:
  soundcloud:
  weibo:
  flickr:
  codepen: